# Generated by Django 5.2.8 on 2026-03-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
