# Generated by Django 5.2.8 on 2026-03-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_alter_projectitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
