# Generated by Django 5.2.8 on 2026-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_alter_project_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectItem',
            new_name='Project_Item',
        ),
        migrations.AddField(
            model_name='project',
            name='overhead',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='margin',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='tax',
            field=models.FloatField(default=12),
        ),
    ]
