# Generated by Django 5.2.8 on 2026-03-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_rename_projectitem_project_item_project_overhead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_per_hour', models.FloatField(default=0)),
                ('hours_per_day', models.FloatField(default=0)),
                ('days_per_month', models.FloatField(default=18)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labors', to='quotation.project')),
            ],
        ),
    ]
