# Generated by Django 5.2.8 on 2026-03-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(max_length=255)),
                ('lead_source', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('estimated_budget', models.FloatField()),
                ('deadline', models.DateField()),
                ('notes', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
